package main

import (
	"encoding/json"
	"fmt"
	"html/template"
	"io/ioutil"
	"os"
	"path/filepath"
	"time"
)

// Wrapper for the data coming from TypeScript filter
type Post struct {
	ID             string  `json:"id"`
	Text           string  `json:"text"`
	Source         string  `json:"source"`
	RelevanceScore float64 `json:"relevanceScore"`
	Category       string  `json:"category"`
	Reasoning      string  `json:"reasoning"`
}

type DigestData struct {
	Date  string
	Posts []Post
}

func main() {
	inputPath := filepath.Join("filtering", "filtered_feed.json")
	outputPath := filepath.Join("weekly_digest.html")

	fmt.Println("Reading filtered feed in Go...")

	// Read JSON file
	file, err := ioutil.ReadFile(inputPath)
	if err != nil {
		fmt.Printf("Error reading file: %v\n", err)
		fmt.Println("Make sure to run the TypeScript filter first.")
		return
	}

	var posts []Post
	err = json.Unmarshal(file, &posts)
	if err != nil {
		fmt.Printf("Error parsing JSON: %v\n", err)
		return
	}

	// Generate HTML
	generateHTML(posts, outputPath)
}

func generateHTML(posts []Post, outputPath string) {
	const tpl = `
<!DOCTYPE html>
<html>
<head>
	<title>Social Wellness Digest</title>
	<style>
		body { font-family: 'Helvetica Neue', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }
		h1 { color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; }
		.intro { color: #7f8c8d; margin-bottom: 40px; }
		.post { background: #f9f9f9; padding: 20px; margin-bottom: 20px; border-radius: 8px; border-left: 5px solid #3498db; }
		.meta { font-size: 0.85em; color: #95a5a6; margin-bottom: 10px; }
		.score { float: right; font-weight: bold; color: #27ae60; }
		.content { font-size: 1.1em; line-height: 1.6; }
		.reasoning { margin-top: 15px; font-size: 0.9em; background: #fff; padding: 10px; border-radius: 4px; border: 1px solid #eee; color: #666; }
		.footer { margin-top: 50px; text-align: center; color: #bdc3c7; font-size: 0.8em; }
	</style>
</head>
<body>
	<h1>Weekly Social Digest</h1>
	<p class="intro">Your curated feed for {{ .Date }}. Optimized for mental clarity.</p>

	{{ range .Posts }}
	<div class="post">
		<div class="meta">
			{{ .Source }} 
			<span class="score">Score: {{ .RelevanceScore }}</span>
		</div>
		<div class="content">
			{{ .Text }}
		</div>
		<div class="reasoning">
			<strong>Why this?</strong> {{ .Reasoning }}
		</div>
	</div>
	{{ else }}
	<p>No high-relevance posts found this week. Enjoy your free time!</p>
	{{ end }}

	<div class="footer">
		Generated by DigestArchitect | Radical Utility Ecosystem
	</div>
</body>
</html>`

	t, err := template.New("digest").Parse(tpl)
	if err != nil {
		panic(err)
	}

	data := DigestData{
		Date:  time.Now().Format("Jan 02, 2006"),
		Posts: posts,
	}

	f, err := os.Create(outputPath)
	if err != nil {
		panic(err)
	}
	defer f.Close()

	err = t.Execute(f, data)
	if err != nil {
		panic(err)
	}

	fmt.Printf("Digest generated successfully: %s\n", outputPath)
}
